name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material

      - name: Build MkDocs site
        run: |
          mkdocs build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-site
          path: ./site

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: built-site

      - name: Setup Git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create a commit
        run: |
          cd ${{ env.GITHUB_WORKSPACE }}/site
          git init
          git add .
          git commit -m "Deploy updated documentation"

      - name: Push the commit or tag
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/guanyu-1/mkdocx_my_page.git
          git push origin gh-pages